#Docker file to create ImageMagick & Java image
FROM centos:7.7.1908

USER root

RUN yum update -y

RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

RUN yum install -y https://imagemagick.org/download/linux/CentOS/x86_64/ImageMagick-libs-7.0.10-6.x86_64.rpm

RUN yum install -y https://imagemagick.org/download/linux/CentOS/x86_64/ImageMagick-7.0.10-6.x86_64.rpm

RUN yum install -y \
       java-11-openjdk-11.0.6.10-1.el7_7 \ 
    && echo "securerandom.source=file:/dev/urandom" >> /usr/lib/jvm/jre/lib/security/java.security \
    && yum clean all

ENV JAVA_HOME /etc/alternatives/jre


